name: Non OMV tests

on:
  push:
    branches: [ master, development, experimental ]
  pull_request:
    branches: [ master, development, experimental ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, "3.10" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Generate NeuroML version
      run: |

        cd NeuroML
        pip install pyneuroml pyNN

        python GenerateNeuroMLlite.py -nml

        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        pip install scipy sympy matplotlib cython pandas tables

        omv install NEURON
        export NEURON_HOME=$pythonLocation # so that pynml can find neuron/nrnivmodl etc.

    - name: Regenerate and run in subfolders
      run: |

        cd NeuroML
        ./regenerateAndTest.sh

    - name: Test Sweep script
      run: |

        cd NeuroML
        python Sweep.py

